<?php require VIEWS_PATH . 'includes/header.phtml';?>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron text-center">
    <h1>Erro 404</h1>
</div>

<div class="container">
    <div class="row">

            <div class="col-sm-12 col-md-12 text-center">
                <img src="https://via.placeholder.com/350" alt="" class="img-responsive">
                <h1> Página não encontrada!</h1>
            </div>

    </div>
</div>

<hr>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
